# DM PYTHON

Importation des données :

In [14]:
import pandas as pd

df = pd.read_csv(
    'https://www.data.gouv.fr/fr/datasets/r/182268fc-2103-4bcb-a850-6cf90b02a9eb'
)
df.head()

/tmp/ipykernel_7930/1661597950.py:3: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix
0,01,Ain,1,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3
1,01,Ain,2,L'Abergement-de-Varey,Nathalie,ARTHAUD,2
2,01,Ain,4,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38
3,01,Ain,5,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8
4,01,Ain,6,Ambléon,Nathalie,ARTHAUD,0

Question 1 :

In [15]:
df["code_commune"] = (
    df["code_departement"].astype(str)
    + df["code_commune"].astype(str).str.zfill(3)
)
df.head(50)

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix
0,01,Ain,01001,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3
1,01,Ain,01002,L'Abergement-de-Varey,Nathalie,ARTHAUD,2
2,01,Ain,01004,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38
3,01,Ain,01005,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8
4,01,Ain,01006,Ambléon,Nathalie,ARTHAUD,0
5,01,Ain,01007,Ambronay,Nathalie,ARTHAUD,10
6,01,Ain,01008,Ambutrix,Nathalie,ARTHAUD,2
7,01,Ain,01009,Andert-et-Condon,Nathalie,ARTHAUD,1
8,01,Ain,01010,Anglefort,Nathalie,ARTHAUD,5
9,01,Ain,01011,Apremont,Nathalie,ARTHAUD,0
10,01,Ain,01012,Aranc,Nathalie,ARTHAUD,4
11,01,Ain,01013,Arandas,Nathalie,ARTHAUD,1
12,01,Ain,01014,Arbent,Nathalie,ARTHAUD,7
13,01,Ain,01015,Arboys en Bugey,Nathalie,ARTHAUD,0
14,01,Ain,01016,Arbigny,Nathalie,ARTHAUD,1
15,01,Ain,01017,Argis,Nathalie,ARTHAUD,1
16,01,Ain,01019,Armix,Nathalie,ARTHAUD,0
17,01,Ain,01021,Ars-sur-Formans,Nathalie,ARTHAUD,2
18,01,Ain,01022,Artemare,Nathalie,ARTHAUD,7
19,01,Ain,01023,Asnières-sur-Saône,Nathalie,ARTHAUD,0
20,01,Ain,01024,Attignat,Nathalie,ARTHAUD,7
21,01,Ain,01025,Bâgé-Dommartin,Nathalie,ARTHAUD,11
22,01,Ain,01026,Bâgé-le-Châtel,Nathalie,ARTHAUD,2
23,01,Ain,01027,Balan,Nathalie,ARTHAUD,7
24,01,Ain,01028,Baneins,Nathalie,ARTHAUD,3
25,01,Ain,01029,Beaupont,Nathalie,ARTHAUD,1
26,01,Ain,01030,Beauregard,Nathalie,ARTHAUD,2
27,01,Ain,01031,Bellignat,Nathalie,ARTHAUD,7
28,01,Ain,01032,Béligneux,Nathalie,ARTHAUD,11
29,01,Ain,01033,Valserhône,Nathalie,ARTHAUD,42
30,01,Ain,01034,Belley,Nathalie,ARTHAUD,28
31,01,Ain,01035,Belleydoux,Nathalie,ARTHAUD,1
32,01,Ain,01036,Valromey-sur-Seran,Nathalie,ARTHAUD,7
33,01,Ain,01037,Bénonces,Nathalie,ARTHAUD,2
34,01,Ain,01038,Bény,Nathalie,ARTHAUD,2
35,01,Ain,01039,Béon,Nathalie,ARTHAUD,1
36,01,Ain,01040,Béréziat,Nathalie,ARTHAUD,0
37,01,Ain,01041,Bettant,Nathalie,ARTHAUD,3
38,01,Ain,01042,Bey,Nathalie,ARTHAUD,1
39,01,Ain,01043,Beynost,Nathalie,ARTHAUD,11
40,01,Ain,01044,Billiat,Nathalie,ARTHAUD,3
41,01,Ain,01045,Birieux,Nathalie,ARTHAUD,0
42,01,Ain,01046,Biziat,Nathalie,ARTHAUD,1
43,01,Ain,01047,Blyes,Nathalie,ARTHAUD,4
44,01,Ain,01049,La Boisse,Nathalie,ARTHAUD,4
45,01,Ain,01050,Boissey,Nathalie,ARTHAUD,1
46,01,Ain,01051,Bolozon,Nathalie,ARTHAUD,2
47,01,Ain,01052,Bouligneux,Nathalie,ARTHAUD,0
48,01,Ain,01053,Bourg-en-Bresse,Nathalie,ARTHAUD,82
49,01,Ain,01054,Bourg-Saint-Christophe,Nathalie,ARTHAUD,4

In [16]:
df[df["libelle_commune"].str.contains("Montrouge", na=False)][["code_departement", "code_commune"]].head(3)

       code_departement code_commune
34535                92        92049
69780                92        92049
105025               92        92049

question 2 :

In [19]:
df["candidat"] = df["prenom"] + " " + df["nom"]
df["candidat"].unique()
candidats = df["candidat"].dropna().nunique()
f"En 2022, il y avait {candidats} candidats à l'élection présidentielle."

"En 2022, il y avait 12 candidats à l'élection présidentielle."

question 3 :

In [23]:
df.groupby("candidat")["voix"].sum()

candidat
Anne HIDALGO              616478
Emmanuel MACRON          9783058
Fabien ROUSSEL            802422
Jean LASSALLE            1101387
Jean-Luc MÉLENCHON       7712520
Marine LE PEN            8133828
Nathalie ARTHAUD          197094
Nicolas DUPONT-AIGNAN     725176
Philippe POUTOU           268904
Valérie PÉCRESSE         1679001
Yannick JADOT            1627853
Éric ZEMMOUR             2485226
Name: voix, dtype: int64

In [24]:
df["candidat"].isna().sum()

np.int64(105735)

In [26]:
scores_nationaux = df.groupby("candidat")["voix"].sum().reset_index()
scores_nationaux.columns = ["candidat", "votes"]

total_exprime = scores_nationaux["votes"].sum()

scores_nationaux["score"] = (scores_nationaux["votes"] / total_exprime * 100).round(2)

scores_nationaux.sort_values("votes", ascending=False).reset_index(drop=True)

                 candidat    votes  score
0         Emmanuel MACRON  9783058  27.85
1           Marine LE PEN  8133828  23.15
2      Jean-Luc MÉLENCHON  7712520  21.95
3            Éric ZEMMOUR  2485226   7.07
4        Valérie PÉCRESSE  1679001   4.78
5           Yannick JADOT  1627853   4.63
6           Jean LASSALLE  1101387   3.13
7          Fabien ROUSSEL   802422   2.28
8   Nicolas DUPONT-AIGNAN   725176   2.06
9            Anne HIDALGO   616478   1.75
10        Philippe POUTOU   268904   0.77
11       Nathalie ARTHAUD   197094   0.56